### ISSUE TITLE
Make tolerations and affinity configurable

### ISSUE THREAD

**Issue by drpebcak** [spotinst/spotinst-kubernetes-helm-charts#20]
**What would you like to be added?**
Configurable values for tolerations and nodeAffinity

**Why is this needed?**
An RKE cluster does not have the `node-role.kubernetes.io/master` label on it, so scheduling this would require adding that extra label.. but even after that label is added, the master nodes have other taints that this deployment does not tolerate by default. Allowing these to be configured would resolve this issue.

**Comment by liranp** [comment]
Merged #21, thank you!
