### ISSUE TITLE
Enable to overwrite the repository of the docker image

### ISSUE THREAD

**Issue by swimablefish** [spotinst/spotinst-kubernetes-helm-charts#22]
**What happened**:
In China, it will be stuck at pulling docker image sometimes. So we have to copy the docker image to aws ecr, then pull the spotinst-controller from ecr
**What you expected to happen**:
The image's repository can be overwritten
**How to reproduce it (as minimally and precisely as possible):**

**Anything else we need to know:**

**Environment:**

- Helm version (use `helm version`): 2.9.1
- OS (e.g: `cat /etc/os-release`): NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):  Linux ip-10-5-3-138 4.15.0-76-generic #86~16.04.1-Ubuntu SMP Mon Jan 20 11:02:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Others: In China

**Comment by liranp** [comment]
[Fixed](https://github.com/spotinst/spotinst-kubernetes-helm-charts/blob/4c1abafe79edcfaf61482dd0c5c52f3fe33d6788/charts/spotinst-kubernetes-cluster-controller/values.yaml#L38-L41). Can be overwritten with `--set image.repository=foo`.
