### ISSUE TITLE
Permit storing token in a Secret

### ISSUE THREAD

**Issue by hlascelles** [spotinst/spotinst-kubernetes-helm-charts#23]
**Use a Secret to store the token**

The token (as I understand it), is "sensitive". Shouldn't it be in a Secret? This allows preparing the Secret ahead of time, then deploying the chart with Gitops (and non-sensitive values in resource control).

We have a [working implementation](https://github.com/spotinst/spotinst-kubernetes-helm-charts/compare/master...bambooengineering:token-in-secret) of this. If it is thought that the tokens are not sensitive we will switch back to configmaps.

**Comment by hlascelles** [comment]
Any more thoughts on this? We are working from a branch now. I would think this should be a Secret.

**Comment by liranp** [comment]
[Released](https://github.com/spotinst/spotinst-kubernetes-helm-charts/commit/751826ca936f72aad8b6e4351d932ac147571baf). Usage: 
```sh
helm install [...] --set secret.enabled=true
```
