### ISSUE TITLE
Support pre-created Secret with token

### ISSUE THREAD

**Issue by tpolekhin** [spotinst/spotinst-kubernetes-helm-charts#28]
**What would you like to be added?**
Support using pre-created Kubernetes secret with account and token information

**Why is this needed?**
When deploying spotinst-controller you must provide `account`, `token` and `clusterIdentifier` variables. When you install this helm chart manually this is not a big deal, but when it is deployed by any automated solution means that you need to commit those values to your script which is not secure.

**Comment by liranp** [comment]
Fixed in [v1.0.93](https://github.com/spotinst/spotinst-kubernetes-helm-charts/blob/8c978e1ca7/charts/spotinst-kubernetes-cluster-controller/values.yaml#L25-L33). Usage example:
```yaml
helm install myrelease spotinst/spotinst-kubernetes-cluster-controller \
  --set spotinst.token=redacted \
  --set spotinst.account=redacted \
  --set spotinst.clusterIdentifier=redacted \
  --set secret.enabled=true \
  --set secret.create=false \
  --set secret.name=mysecret \
  # [...]
```
