### ISSUE TITLE
Agent job is not started on Azure system pool

### ISSUE THREAD

**Issue by denisp13** [spotinst/spotinst-kubernetes-helm-charts#29]
**Description:**
When ```only_critical_addons_enabled = true``` is  setup for the system\default AKS node pool the job is stuck in Pending state because the pod cannot tolerate the node conditions

```0/10 nodes are available: 3 node(s) had taint {CriticalAddonsOnly: true}, that the pod didn't tolerate, 7 node(s) didn't match node selector.```

**Possible solution:**
Template of the Job should have it is own taint configuration or inherited from the deployment.yaml template
Moreover why to hardcode the Nodeselector? https://github.com/spotinst/spotinst-kubernetes-helm-charts/blob/523af9ef864623176eb6302410de5b8f136a8aa8/charts/spotinst-kubernetes-cluster-controller/templates/job.yaml#L20

**How to reproduce:**
Create a new AKS cluster with configuration
default_node_pool {
    only_critical_addons_enabled = true
  }
**

**Environment:**

- Helm version - v3.5.2
- AKS cluster - 1.19.11
- Node Taints  -CriticalAddonsOnly=true:NoSchedule

**Comment by denisp13** [comment]
We have faced some difficulties which I would like to mention:

1. For the agent installation, we have used the spot.io official helm chart, unfortunately, it didn't work because the Job is bounded to run on the system node pool and doesn't have a taints configuration, however, Azure allows adding a special taint `CriticalAddonsOnly=true:NoSchedule` , which we are using. 

2. When the job is scheduled, it has "pre-install" annotation, which forces Helm to install it before all others resources. 
annotations:
helm.sh/hook: pre-install
helm.sh/hook-weight: "5"
However, the job template relies on the config map and the secret data which will be never created cause the templates are not having the "pre-install" hook annotation. 

3. Helm chart is providing an option to choose a namespace different from "kube-system" however, the cluster import bash script creates the job in the "kube-system"  Namespace, the job is failing because it refers to the secret created by the Helm ( in the other namespace )

Whoever is facing the same problem, you can try out my fix : https://github.com/denisp13/spotinst-kubernetes-helm-charts/tree/feature/job_taints/charts/spotinst-kubernetes-cluster-controller/templates

**Comment by liranp** [comment]
Fixed in [v1.0.93](https://github.com/spotinst/spotinst-kubernetes-helm-charts/blob/8c978e1ca7/charts/spotinst-kubernetes-cluster-controller/values.yaml#L157-L166) -- `aksConnector.tolerations` and `aksConnector.nodeSelector` have been added to `values.yaml`, with default values. If needed, you can override them. Also, we have [added](https://github.com/spotinst/spotinst-kubernetes-helm-charts/blob/8c978e1ca7/charts/spotinst-kubernetes-cluster-controller/templates/config_map.yaml#L10-L15) the `pre-install` annotation so Helm can apply both the `ConfigMap` and the `Secret` before it applies the `Job`. Thank you for bringing this issue to our attention and for proposing a solution!

**Comment by denisp13** [comment]
> added

Hey liranp!
Have you tested your changes?
The prehook annotation will create the resources ( config_map ) only for the job , after the job will be successfully finished all the resources will be deleted , however the deployment template is referring to the same config_map.yaml which is used for the job and eventually the when the helm will try to apply the deployment.yaml it will fail.

**Comment by liranp** [comment]
Hi @denisp13. Sorry about that. My intention was to change *helm.sh/hook-delete-policy*, but I missed it. I've [changed](https://github.com/spotinst/spotinst-kubernetes-helm-charts/commit/6a4bc45f012b8512863f414c6944b9dded5f367d#diff-d37262f9f0ec58d706ad78078ddd9ece88d05587fb5a2c35ee497d2e22be2638R14) it now to `before-hook-creation,hook-failed`.

**Comment by liranp** [comment]
Hi @denisp13. Sorry about that. My intention was to change *helm.sh/hook-delete-policy*, but I missed it. I've [fixed](https://github.com/spotinst/spotinst-kubernetes-helm-charts/blob/0cc4c001d1/charts/spotinst-kubernetes-cluster-controller/templates/job.yaml#L73-L104) it now.
