### ISSUE TITLE
APIService error on GKE  1.20.9-gke.701

### ISSUE THREAD

**Issue by houstondapaz** [spotinst/spotinst-kubernetes-helm-charts#31]
**What happened**: Error on try install controller at GKE
```
W0909 16:57:44.940555    3138 warnings.go:70] rbac.authorization.k8s.io/v1beta1 RoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 RoleBinding
W0909 16:57:45.519344    3138 warnings.go:70] apiregistration.k8s.io/v1beta1 APIService is deprecated in v1.19+, unavailable in v1.22+; use apiregistration.k8s.io/v1 APIService
Error: rendered manifests contain a resource that already exists. Unable to continue with install: APIService "v1beta1.metrics.k8s.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "spotinst-kubernetes-cluster-controller"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"
```
**What you expected to happen**: Install controller at cluster

**How to reproduce it (as minimally and precisely as possible):**
- Create an GKE cluster
```
helm install \
  spotinst-kubernetes-cluster-controller \
  spotinst/spotinst-kubernetes-cluster-controller \
  --version 1.0.77 \
  --namespace kube-system \
  --set spotinst.token=[TOKEN] \
  --set spotinst.account=[ACCOUNT_ID] \
  --set spotinst.clusterIdentifier=[IDENTIFIER]
```

**Anything else we need to know:**

**Environment:**

- Helm version (use `helm version`): 
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
- Kernel (e.g. `uname -a`):
Linux Octa0096 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Others:
GKE private cluster

**Comment by applike-ss** [comment]
Seems you already have a metrics server in your cluster, try setting these values in addition for the chart:
```yaml
metrics-server:
  deployChart: false
```

**Comment by liranp** [comment]
See #33. Thanks for raising that.
