### ISSUE TITLE
Remove deprecation warning

### ISSUE THREAD

**Issue by kuperiu** [spotinst/spotinst-kubernetes-helm-charts#33]
**What would you like to be added?**
Metrics server dependency for spotinst-kubernetes-cluster-controller helm chart needs to be upgraded
https://github.com/spotinst/spotinst-kubernetes-helm-charts/blob/master/charts/spotinst-kubernetes-cluster-controller/requirements.yaml#L3
**Why is this needed?**
That version of Metrics server is using a deprecated api version of RoleBinding that cause this warring and will fail in upgrade clusters
```
warning: rbac.authorization.k8s.io/v1beta1/RoleBinding is deprecated by rbac.authorization.k8s.io/v1/RoleBinding and not supported by Kubernetes v1.22+ clusters.
```

**Comment by hussainsaify** [comment]
Any update on this? This is preventing us to upgrade to 1.22 version, below are the resources using deprecated api versions

```
spotinst-kubernetes-cluster-controller/spotinst-kubernetes-cluster-controller-metrics-server-auth-reader   kube-system              RoleBinding                    rbac.authorization.k8s.io/v1beta1      rbac.authorization.k8s.io/v1      true         v1.17.0         true      v1.22.0     
spotinst-kubernetes-cluster-controller/v1beta1.metrics.k8s.io                                              kube-system              APIService                     apiregistration.k8s.io/v1beta1         apiregistration.k8s.io/v1         true         v1.10.0         true      v1.22.0
```

**Comment by gridley-c** [comment]
Also seeing this one.

**Comment by stevenfeltner** [comment]
@liranp @yeminiori Are you able to review?

**Comment by morditore** [comment]
Until the metrics-server dependency is upgraded, we simply install it separately and then set the `metrics-server.deployChart=false` value in this chart.

**Comment by liranp** [comment]
[Updated](https://github.com/spotinst/spotinst-kubernetes-helm-charts/commit/530716197382b9cc343ae68538ca61dff0b0b3a1) and [released](https://github.com/spotinst/spotinst-kubernetes-helm-charts/commit/b516c9b1d02f5dadc1c66a965cb2591cdcf047a0). Thanks for raising that.

**Comment by MagicGTS** [comment]
Just delete the old APIService definition:
`kubectl delete APIService v1beta1.metrics.k8s.io`
